apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: agente-rh
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: agente-rh
    app.kubernetes.io/component: frontend
  ports:
    - port: 3000
      targetPort: 3000
